In [3]:
!python3 -m pip install mysql-connector-python sqlalchemy pandas

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp314-cp314-macosx_14_0_arm64.whl.metadata (11 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp314-cp314-macosx_11_0_arm64.whl.metadata (9.5 kB)
Collecting pandas
  Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl.metadata (79 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl.metadata (6.6 kB)
Collecting python-dateutil>=2.8.2 (from pandas)
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas)
  Downloading six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading mysql_connector_python-9.6.0-cp314-cp314-macosx_14_0_arm64.whl (17.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 38.7 MB/s  0:00:00 eta 0:00:01
Downloading sqlalchemy-2.0.49-cp314-cp314-macosx_11_0_arm64.whl (2.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 42.5 MB/s  0:00:00
Downloading pandas-3.0.2-cp314-cp314-macosx_11_0_arm64.whl (9.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.9/9.9 MB 46.4 MB/s  0:00:00m0:00:01
Downloading numpy-2.4.4-cp314-cp314-macosx_14_0_arm64.whl (5.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 56.2 MB/s  0:00:00
Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, six, numpy, mysql-connector-python, sqlalchemy, python-dateutil, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7/7 [pandas]2m6/7 [pandas]emy]ctor-python]
Successfully installed mysql-connector-python-9.6.0 numpy-2.4.4 pandas-3.0.2 python-dateutil-2.9.0.post0 six-1.17.0 sqlalchemy-2.0.49 typing-extensions-4.15.0

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip3 install --upgrade pip

In [2]:
!python3 -m pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages (9.6.0)

In [3]:
import sys
print(sys.executable)

/opt/anaconda3/bin/python

In [7]:
!{sys.executable} -m pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp313-cp313-macosx_14_0_arm64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp313-cp313-macosx_14_0_arm64.whl (17.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.6/17.6 MB 37.9 MB/s  0:00:00 eta 0:00:01
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [8]:
import mysql.connector as sql

conn = sql.connect(
    host="localhost",
    user="root",
    password="",
    database="cap4770"
)

print(conn.is_connected())

True

In [9]:
import pandas as pd

pd.read_sql("SHOW TABLES", conn)

/var/folders/f7/58bdmmmd29q37zf5wkxqn3q40000gn/T/ipykernel_35090/884095768.py:3: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql("SHOW TABLES", conn)

  Tables_in_cap4770
0             train

In [10]:
from sqlalchemy import create_engine
import pandas as pd

engine = create_engine("mysql+mysqlconnector://root:@localhost/cap4770")

df_csv = pd.read_csv("/Users/luismadrigal/Downloads/archive/train.csv")

print(df_csv.shape)  # should be ~46244

df_csv.to_sql("train", con=engine, if_exists="replace", index=False)

(46244, 25)

46244

In [12]:
pd.read_sql("SELECT COUNT(*) AS total_rows FROM train", engine)

   total_rows
0       46244

In [13]:
df_test = pd.read_csv("/Users/luismadrigal/Downloads/archive/test.csv")

print(df_test.shape)

df_test.to_sql("test", con=engine, if_exists="replace", index=False)

(65779, 24)

65779

In [14]:
df_park = pd.read_csv("/Users/luismadrigal/Downloads/archive/park_dimensions.csv")

print(df_park.shape)

df_park.to_sql("park_dimensions", con=engine, if_exists="replace", index=False)

(30, 9)

30

In [15]:
pd.read_sql("SHOW TABLES", engine)

  Tables_in_cap4770
0   park_dimensions
1              test
2             train

In [16]:
df_train = pd.read_sql("SELECT * FROM train", engine)

In [17]:
df_test = pd.read_sql("SELECT * FROM test", engine)

In [18]:
df_park = pd.read_sql("SELECT * FROM park_dimensions", engine)

In [19]:
print(df_train.shape)
print(df_test.shape)
print(df_park.shape)

(46244, 25)
(65779, 24)
(30, 9)

In [20]:
df_total = pd.concat([df_train, df_test], ignore_index=True)

In [21]:
print(df_total.shape)
df_total.head()

(112023, 25)

,bip_id,game_date,home_team,away_team,batter_team,batter_name,pitcher_name,batter_id,pitcher_id,is_batter_lefty,...,inning,outs_when_up,balls,strikes,plate_x,plate_z,pitch_mph,launch_speed,launch_angle,is_home_run
0,1,2020-08-26,ARI,COL,COL,"arenado, nolan","ray, robbie",571448,592662,0,...,1,0,1,2,-0.15,1.97,87.8,108.9,9.0,0.0
1,2,2020-08-10,COL,ARI,COL,"arenado, nolan","ray, robbie",571448,592662,0,...,1,1,3,1,-0.71,2.88,95.2,NaN,18.0,0.0
2,3,2020-08-10,COL,ARI,COL,"arenado, nolan","ray, robbie",571448,592662,0,...,3,0,1,2,-0.54,1.75,86.5,75.0,49.0,0.0
3,4,2020-08-26,ARI,COL,COL,"blackmon, charlie","ray, robbie",453568,592662,1,...,1,0,0,2,-0.42,3.15,86.7,90.6,54.0,0.0
4,5,2020-08-10,COL,ARI,COL,"blackmon, charlie","ray, robbie",453568,592662,1,...,1,1,1,0,0.18,3.27,96.1,NaN,6.0,0.0

In [23]:
df_park.head()

,park,NAME,Cover,LF_Dim,CF_Dim,RF_Dim,LF_W,CF_W,RF_W
0,0,Chase Field,Roof,328,407,335,8,25,8
1,1,SunTrust Park,Outdoor,335,400,325,6,8,16
2,2,Oriole Park at Camden Yards,Outdoor,333,400,318,7,7,21
3,3,Fenway Park,Outdoor,310,390,302,37,9,3
4,4,Wrigley Field,Outdoor,355,400,353,16,11,16

In [24]:
df_train.to_csv("train_clean.csv", index=False)
df_test.to_csv("test_clean.csv", index=False)
df_park.to_csv("park_dimensions_clean.csv", index=False)
df_total.to_csv("df_total.csv", index=False)

In [25]:
import os
os.getcwd()

'/Users/luismadrigal/anaconda_projects/07dd458b-3d25-40a6-b564-b12287d7cedd'